spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: test
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_agile?allowPublicKeyRetrieval=true&useSSL=false
  freemarker:
    template-loader-path: classpath:/mail-templates/
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false


logging:
  level:
    org.springframework.security: DEBUG

app:
  mail-from: noreply@taskagile.com
  token-secret-key: 60dKuW2Qpc3YkUoaa9i6qY5cyaGgQM8clfxpDGWS3sY=